repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        pass_filenames: true
        exclude: ^(tests/|doc/|conftest\.py)
        additional_dependencies:
          - pydantic>=2.6.0
          - types-PyYAML
          - types-requests
          - SQLAlchemy>=2.0.25
          - httpx>=0.27.0
