apiVersion: v1
kind: Secret
metadata:
  name: autotest-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: autotest-platform
type: Opaque
stringData:
  PGPASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  AUTOTEST_DB_URL: "postgresql+asyncpg://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include \"autotest-platform.postgresHost\" . }}:5432/{{ .Values.postgres.auth.database }}"
  AUTH_JWT_SECRET: {{ .Values.config.auth.jwtSecret | quote }}
  AUTH_DEFAULT_ADMIN_PASSWORD: {{ .Values.config.auth.defaultAdmin.password | quote }}
  API_KEY: {{ .Values.secrets.apiKey | quote }}
