"""init: create all tables

Revision ID: 46c790b96d37
Revises: 
Create Date: 2026-06-05 17:48:12.843555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c790b96d37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='用例名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='用例描述'),
    sa.Column('yaml_content', sa.Text(), nullable=True, comment='原始 YAML 内容'),
    sa.Column('tags', sa.Text(), nullable=True, comment='标签列表（JSON 数组）'),
    sa.Column('priority', sa.String(length=10), nullable=False, comment='优先级: P0/P1/P2/P3'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active/archived'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_suites',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='套件名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='套件描述'),
    sa.Column('config', sa.Text(), nullable=True, comment='套件配置（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('suite_id', sa.UUID(), nullable=True, comment='关联套件 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending/running/passed/failed/error/timeout'),
    sa.Column('trigger', sa.String(length=20), nullable=False, comment='触发方式: manual/schedule/api'),
    sa.Column('env', sa.String(length=50), nullable=True, comment='执行环境'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增主键'),
    sa.Column('execution_id', sa.UUID(), nullable=False, comment='关联执行记录 ID'),
    sa.Column('case_id', sa.UUID(), nullable=True, comment='关联用例 ID'),
    sa.Column('case_name', sa.String(length=255), nullable=True, comment='用例名称（冗余，便于查询）'),
    sa.Column('passed', sa.Boolean(), nullable=False, comment='是否通过'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='详细状态: PASS/FAIL/SKIP/TIMEOUT/ERROR'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('request', sa.Text(), nullable=True, comment='请求内容（JSON）'),
    sa.Column('response', sa.Text(), nullable=True, comment='响应内容（JSON）'),
    sa.Column('elapsed_ms', sa.Float(), nullable=True, comment='耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_results_execution_id'), 'execution_results', ['execution_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 UUID'),
    sa.Column('execution_id', sa.UUID(), nullable=False, comment='关联执行记录 ID'),
    sa.Column('summary', sa.Text(), nullable=True, comment='报告摘要（JSON）'),
    sa.Column('detail_data', sa.Text(), nullable=True, comment='详细数据（JSON）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index(op.f('ix_execution_results_execution_id'), table_name='execution_results')
    op.drop_table('execution_results')
    op.drop_table('executions')
    op.drop_table('test_suites')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
